version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./docker_files/master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=S3cret
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20

  database_slave:
    image: mysql:8.0.30
    container_name: "database_slave"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 3307:3306
    volumes:
      - ./docker_files/slave.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=S3cret
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
networks:
  mynetwork:
